mysite/api/urls.py
from django.urls import path, include
from .views import *

app_name = 'api'

urlpatterns = [
    path('recipe/', RecipeList.as_view(), name='recipe-list'),
    path('recipe/<int:pk>', RecipeDetail.as_view(), name='recipe-detail'),
]

mysite/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.recipe_list, name='recipe_list'),
    path('<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('search/<str:search_type>/<str:chart_label>/', views.chart_search_list, name='recipe_search'),
    path('visual/', views.visual_detail, name='visual')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include('dashboard.urls')),
    path('api/', include('api.urls')),
]

mysite/api/models.py
from django.db import models

# Create your models here.

mysite/dashboard/models.py
from django.db import models

# Create your models here.
class Recipe(models.Model):
    recipe_title = models.CharField(max_length=200, verbose_name='레시피명')
    link = models.CharField(max_length=200, verbose_name='레시피 링크', null=True)
    time = models.IntegerField(verbose_name='요리 시간', null=True)
    servings = models.IntegerField(verbose_name='인분', null=True)
    image_url = models.CharField(max_length=300, verbose_name='이미지 링크', null=True)
                                
    def __str__(self):
        return f'레시피: {self.recipe_title}, 요리 시간 : {self.time}, 요리 인분 : {self.servings}'


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, related_name='ingredients', on_delete=models.CASCADE)
    ingredient = models.CharField(max_length=200, verbose_name='재료')
    
    def __str__(self):
        return self.ingredient


class RecipeOrder(models.Model):
    recipe = models.ForeignKey(Recipe, related_name='recipe_orders', on_delete=models.CASCADE)
    order = models.CharField(max_length=500, verbose_name='레시피 순서')

    def __str__(self):
        return f'{self.recipe} : {self.order}'
    

mysite/api/views.py
from django.shortcuts import render
from dashboard.models import Recipe, Ingredient
from api.serializers import RecipeSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status, generics, permissions


# Create your views here.
class RecipeList(generics.ListCreateAPIView):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer


class RecipeDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer

mysite/dashboard/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse 
from mysite import settings
from .models import *
from collections import Counter
import json
import pandas as pd
import random

def visual_detail(request):
    recipes = Recipe.objects.all()
    
    ingredients = Ingredient.objects.all()
    ingredient_counts = Counter(ingredient.ingredient for ingredient in ingredients)

    top_ingredients = ingredient_counts.most_common()
    labels = [ingredient[0] for ingredient in top_ingredients]
    data = [ingredient[1] for ingredient in top_ingredients]

    # 요리 시간 구하기
    cook_time = (pd.cut(pd.Series([i.time for i in Recipe.objects.all()]), [-1, 10, 20, 30, 60, 90, 121])
                 .value_counts()
                 .sort_index()
                 .reset_index()
                 )
    cook_time.loc[:, 'index'] = ['10분 미만', '10~20분', '20~30분', '30~60분', '60~90분', '90~120분']
    
    # 랜덤 레시피 선택
    random_recipe = random.choice(recipes) if recipes else None

    return render(request, 'visual_detail.html', {
        'recipes': recipes,
        'random_recipe': random_recipe,
        'labels_json': json.dumps(labels, ensure_ascii=False),
        'data_json': json.dumps(data),
        'ingredients_json': json.dumps([{'name': name, 'frequency': freq} for name, freq in top_ingredients], ensure_ascii=False),
        'cook_time_label': cook_time['index'].tolist(),
        'cook_time_data': cook_time['count'].tolist(),
    })

def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    orders_with_index = enumerate([i.order for i in recipe.recipe_orders.all()])
    
    # 추천 상품 구하기
    def get_random_recipe():
        return Recipe.objects.order_by("?").first()
    
    random_recipe = [get_random_recipe() for _ in range(4)]
    
    return render(request, 'recipe_detail.html', {
        'recipe': recipe,
        'orders_with_index' : orders_with_index,
        'random_recipe' : random_recipe,
        })

def recipe_list(request):
    recipes = Recipe.objects.all()
    
    # 재료 빈도수 계산
    ingredients = Ingredient.objects.all()
    ingredient_counts = Counter(ingredient.ingredient for ingredient in ingredients)
    
    # 가장 빈도가 높은 15개 재료 가져오기
    top_ingredients = ingredient_counts.most_common(20)
    labels = [ingredient[0] for ingredient in top_ingredients]
    data = [ingredient[1] for ingredient in top_ingredients]

    # 요리 시간 구하기
    cook_time = (pd.cut(pd.Series([i.time for i in Recipe.objects.all()]), [-1, 10,20,30,60,90,121])
                 .value_counts()
                 .sort_index()
                 .reset_index()
                 )
    cook_time.loc[:, 'index'] = ['10분 미만', '10~20분', '20~30분', '30~60분', '60~90분', '90~120분']

    return render(request, 'index.html', {
        'recipes': recipes,
        'labels_json': json.dumps(labels, ensure_ascii=False),
        'data_json': json.dumps(data),
        'ingredients_json': json.dumps([{'name': name, 'frequency': freq} for name, freq in top_ingredients], ensure_ascii=False),
        'cook_time_label' : cook_time['index'].tolist(),
        'cook_time_data' : cook_time['count'].tolist(),
    })
    
def chart_search_list(request, search_type, chart_label):
    # 요리 시간 구하기 (dataFrame 인덱스를 기준으로 필터링)
    cook_time = pd.DataFrame([i.time for i in Recipe.objects.all()], columns = ['time']) 
    cook_time['time_split'] = pd.cut(cook_time['time'], [-1, 10,20,30,60,90,121])
    mapping_dict = {i : v for i, v in zip(cook_time['time_split'].value_counts().sort_index().index, ['10분 미만', '10~20분', '20~30분', '30~60분', '60~90분', '90~120분'])}
    cook_time['time_split_mapping'] = cook_time['time_split'].apply(lambda x : mapping_dict[x])
    
    # 재료 매핑
    cook_time['isin_ingredient'] = [len(i.ingredients.all().filter(ingredient__icontains=chart_label)) != 0 for i in Recipe.objects.all()]
    
    if search_type == 'time':
        search_result_recipe = [obj for idx, obj in enumerate(Recipe.objects.all()) if idx in cook_time[cook_time['time_split_mapping'] == chart_label].index.tolist()]
    elif search_type == 'ingredient':
        search_result_recipe = [obj for idx, obj in enumerate(Recipe.objects.all()) if idx in cook_time[cook_time['isin_ingredient'] == True].index.tolist()]
    else:
        search_result_recipe = None
    
    return render(request, 'serach_result.html', {
        'search_result_recipe' : search_result_recipe,
        'search_type' : search_type,
        'chart_label' : chart_label
    })

mysite/dashboard/templates/header.html
<!-- header.html -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);">
    <div class="container px-4 px-lg-5 d-flex justify-content-between align-items-center">
        <!-- 왼쪽 타이틀 -->
        <a class="navbar-title" href="{% url 'dashboard:recipe_list' %}" style="text-decoration: none;">
            만개의 레시피 재료 분석
        </a>

        <!-- 중앙 검색 입력 필드 -->
        <form id="search-form" class="d-flex" onsubmit="return handleSearch(event);" style="flex-grow: 1; justify-content: center;">
            <div class="input-group" style="max-width: 400px;"> <!-- 검색창 최대 크기 조정 -->
                <input type="text" id="search-input" class="form-control" placeholder="검색할 재료" aria-label="Search" required style="border-radius: 25px 0 0 25px; border: 1px solid #3cb44b;">
                <button type="submit" class="btn btn-success" style="border-radius: 0 25px 25px 0;">검색</button>
            </div>
        </form>

        <!-- 오른쪽으로 이동된 시각화 페이지로 가는 버튼 -->
        <a href="{% url 'dashboard:visual' %}" class="btn btn-success" style="border-radius: 25px; white-space: nowrap;">시각화 페이지로 이동</a>
    </div>
</nav>

<style>
    .navbar {
        background-color: #f0f4f8; /* 부드러운 배경색 */
    }

    .navbar-title {
        font-size: 36px;
        font-weight: 700;
        color: #3cb44b;
        text-align: center;
        letter-spacing: 2px;
        font-family: 'Noto Sans KR', sans-serif;
    }

    .form-control {
        font-size: 16px;
        padding: 10px 15px; /* 패딩 조정 */
    }

    .btn-success {
        background-color: #3cb44b;
        border: none;
        padding: 10px 20px;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    .btn-success:hover {
        background-color: #32a52b; /* 버튼 hover 색상 */
    }

    .input-group {
        width: auto; /* 입력 필드와 버튼을 한 줄로 표시 */
    }
</style>

<script>
    function handleSearch(event) {
        event.preventDefault(); // 폼 제출 방지
        const query = document.getElementById('search-input').value.trim();

        if (query) {
            // 검색 결과 페이지로 이동 (URL을 적절히 변경)
            const url = "{% url 'dashboard:recipe_search' 'ingredient' 'label_placeholder' %}";
            window.location.href = url.replace('label_placeholder', encodeURIComponent(query));
        }
    }
</script>

mysite/dashboard/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>만개의 레시피 재료 분석</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/lumen/bootstrap.min.css" />
    <!-- Chart Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- WordCloud -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wordcloud2.js/1.2.2/wordcloud2.min.js"></script>
  </head>
  <style>
    /* Custom scrollbar */

    .col-md-3::-webkit-scrollbar {
      width: 8px;
    }
    
    .col-md-3::-webkit-scrollbar-thumb {
      background-color: #3cb44b;
      border-radius: 10px;
      border: 2px solid #ffffff;
    }
    
    .col-md-3::-webkit-scrollbar-track {
      margin-top: 5px;
      margin-bottom: 5px;
      background-color: #ffffff;
      border-radius: 10px;
    }
    
    .img-fluid:hover {
      transform: scale(1.1); /* 살짝 확대 */
      box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.3); /* 그림자 더 강하게 */
      transition: transform 0.3s ease, box-shadow 0.3s ease; /* 부드러운 전환 */
    }
    
    /* 링크 텍스트 색상 변경 */
    .recipe-container:hover .rank-title a {
      color: #3cb44b; /* 텍스트 색상을 초록색으로 변경 */
      text-decoration: underline; /* 밑줄 추가 */
    }
  </style>
  <body>
    <!-- Navigation -->

    {% block navbar %}
      {% include 'header.html' %}
    {% endblock %}

    <div class="overlay" id="overlay" style="display: none;">
      <h1>환영합니다!</h1>
      <p>재형 효정 주호가 제작한 만개의 레시피 재료 분석 프로젝트입니다!</p>
    </div>

    <style>
      .overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(255, 255, 255, 0.9);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        z-index: 1000;
        transition: opacity 0.8s ease; /* 사라지는 시간을 0.8초로 설정 */
        opacity: 1;
      }
      
      .main-content {
        display: none; /* 메인 콘텐츠를 처음에 숨깁니다. */
      }
      
      .main-content.show {
        display: block; /* show 클래스가 추가되면 보이게 합니다. */
      }
      
      .overlay h1 {
        font-size: 48px;
        color: #3cb44b;
        margin-bottom: 20px;
      }
      
      .overlay p {
        font-size: 18px;
        text-align: center;
      }
    </style>


    <script>
      // 페이지가 로드될 때 오버레이를 확인합니다.
      window.onload = function () {
        const overlay = document.getElementById('overlay')
        const mainContent = document.getElementById('main-content')
      
        // 최초 방문 여부를 확인
        if (!localStorage.getItem('hasVisited')) {
          overlay.style.display = 'flex' // 오버레이를 보여줍니다.
      
          // 오버레이가 사라진 후 메인 콘텐츠를 표시합니다.
          overlay.addEventListener('click', function () {
            overlay.style.opacity = '0'
            overlay.style.pointerEvents = 'none' // 클릭 방지를 위해
            setTimeout(() => {
              mainContent.classList.add('show')
            }, 800) // 오버레이가 사라지는 시간과 일치시킴
          })
      
          // 최초 방문 여부를 기록합니다.
          localStorage.setItem('hasVisited', 'true')
        } else {
          mainContent.classList.add('show') // 이미 방문한 경우 바로 콘텐츠를 표시
        }
      }
    </script>

    <section class="py-0">
      <div class="container px-4 px-lg-5 my-5">
        <div class="row">
          <!-- 왼쪽 영역: Bar Chart, Doughnut Chart, WordCloud -->
          <div class="col-md-9">
            <div class="row gx-4 gx-lg-5 align-items-start">
              <!-- align-items-start 추가 -->
              <div class="col-md-12">
                <!-- Bar Plot -->
                <div style="border: 2px solid #3cb44b; border-radius: 15px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); padding: 10px; margin-bottom: 20px;">
                  <h5 style="text-align: center; margin: 10px 0; font-weight: bold; top: 0; background-color: white; z-index: 10; font-family: 'Noto Sans KR', sans-serif; font-weight: bold; color: #3cb44b;">많이 이용한 재료!</h5>
                  <canvas id="barChart" width="400" height="200"></canvas>
                </div>

                <!-- Doughnut Chart -->
                <div style="border: 2px solid #3cb44b; border-radius: 15px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); padding: 10px; margin-top: 20px;">
                  <h5 style="text-align: center; margin: 10px 0; font-weight: bold; top: 0; background-color: white; z-index: 10; font-family: 'Noto Sans KR', sans-serif; font-weight: bold; color: #3cb44b;">조리 소요 시간!</h5>
                  <canvas id="piChart" width="400" height="200"></canvas>
                </div>

                <!-- Word Cloud -->
                <div id="wordcloud" style="height: 300px; width: 100%; margin-top: 20px; margin-bottom: 20px; border: 2px solid #3cb44b; border-radius: 15px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); overflow: hidden;"></div>
              </div>
            </div>
          </div>
          <!-- 오른쪽 영역: 레시피 랭킹 -->
          <div class="col-md-3" style="height: 1165px; overflow-y: auto; position: relative; padding: 0px; border: 2px solid #3cb44b; border-radius: 15px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);">
            <h2 class="text-center mb-3" style="position: sticky; top: 0; background-color: white; z-index: 10; font-family: 'Noto Sans KR', sans-serif; font-weight: bold; color: #3cb44b; padding: 10px; border-bottom: 1px solid #3cb44b; font-size: 1.5rem;">레시피 랭킹</h2> <!-- 글자 크기 줄임 -->
          
            {% for recipe in recipes %}
              <div class="mb-4 recipe-container" style="padding: 10px; font-family: 'Noto Sans KR', sans-serif;">
                <div class="rank-title" style="font-weight: bold; font-size: 1.2rem; color: #333333; padding-bottom: 5px;"> <!-- 글자 크기 줄임 -->
                  <a href="{% url 'dashboard:recipe_detail' recipe.id %}" style="color: #333333; text-decoration: none;">{{ forloop.counter }}위: {{ recipe.recipe_title }}</a>
                </div>
                <div class="text-center">
                  <a href="{% url 'dashboard:recipe_detail' recipe.id %}"><img src="{{ recipe.image_url }}" alt="{{ recipe.recipe_title }}" class="img-fluid" style="width: 250px; height: 180px; object-fit: cover; border: 1px solid #dddddd; border-radius: 10px; box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);" /></a>
                </div>
              </div>
              <div style="border-bottom: 1px solid #cccccc; margin: 0 20px; margin-bottom: 10px;" class="mb-3"></div> <!-- 아래 간격 조정 -->
            {% endfor %}
          </div>
          
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="py-3 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">재형 효정 주호</p>
      </div>
    </footer>

    <script> 
    {% comment %} WordCloud {% endcomment %}
    document.addEventListener('DOMContentLoaded', function() {
      const ingredients = {{ ingredients_json|safe }};
      
      const frequencies = ingredients.map(ing => ing.frequency);
      const maxFreq = Math.max(...frequencies);
      const minFreq = Math.min(...frequencies);
      
      const linearScale = (val, minVal, maxVal, newMin, newMax) => {
          return newMin + (val - minVal) * (newMax - newMin) / (maxVal - minVal);
      };
  
      const words = ingredients.map(ingredient => [
          ingredient.name,
          Math.max(5, Math.floor(linearScale(ingredient.frequency, minFreq, maxFreq, 10, 80)))
      ]);
  
      console.log("Words for WordCloud:", words);
  
      const colors = [
        '#ffadad', '#ffd6a5', '#fdffb6', '#caffbf', '#9bfbc0',
        '#a0c4ff', '#b9fbc0', '#ffc3a0', '#ff677d', '#d4a5a5',
        '#392f5a', '#b8e4f8', '#ff9a00', '#b4f8e1', '#a5e8d4',
        '#d0d3e2', '#ffe156', '#ff6f61', '#f7d2c0',
      ];
      WordCloud(document.getElementById('wordcloud'), {
        list: words,
        gridSize: 10,
        weightFactor: 2.2,
        fontFamily: 'Noto Sans KR, sans-serif',
        color: function() {
            return colors[Math.floor(Math.random() * colors.length)];
        },
        backgroundColor: 'white',
        rotateRatio: 0.5,
        rotationSteps: 0,
        drawOutOfBound: false,
        shrinkToFit: true,
        shape: 'circle',
        minSize: 10,
        // 클릭 이벤트 리스너 추가
        click: function(item) {
          var url = "{% url 'dashboard:recipe_search' 'search_type' 'label_placeholder' %}";
          url = url.replace('search_type', encodeURIComponent('ingredient'));
          url = url.replace('label_placeholder', encodeURIComponent(item[0])); 
          window.location.href = url; 
      }
    });
    
  
      // 바 차트 설정
      var canvasB = document.getElementById("barChart");
      const ctx = canvasB.getContext('2d');
      const barChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: {{ labels_json|safe }},
              datasets: [{
                  label: '레시피 수',
                  data: {{ data_json|safe }},
                  backgroundColor: 'rgba(75, 192, 192, 0.2)',
                  borderColor: 'rgba(75, 192, 192, 1)',
                  borderWidth: 1,
                  hoverBackgroundColor: 'rgba(220, 0, 0, 0.7)',
                  hoverBorderColor: 'rgba(220, 0, 0, 0.7)',
              }]
          },
          options: {
              scales: {
                  y: {
                      beginAtZero: true
                  }
              }
          }
      });
  
      // 바 차트 클릭 이벤트
      canvasB.onclick = function(e) {
          var slice = barChart.getElementAtEvent(e);
          if (!slice.length) return; // return if not clicked on slice
          var label = slice[0]._model.label;
          var url = "{% url 'dashboard:recipe_search' 'search_type' 'label_placeholder' %}";
          url = url.replace('search_type', encodeURIComponent('ingredient'));
          url = url.replace('label_placeholder', encodeURIComponent(label));
          window.location.href = url;
      }
  });

    {% comment %} 조리 소요 시간 {% endcomment %}
    var canvasP = document.getElementById("piChart");
    const ctx2 = document.getElementById('piChart').getContext('2d');
    const piChart = new Chart(ctx2, {
        type: 'doughnut',
        data: {
            labels: {{ cook_time_label|safe }},
            datasets: [{
                data: {{ cook_time_data|safe }},
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                    ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                    ],
                hoverBackgroundColor : [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                    ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    position: 'top' // 범례의 위치 설정
                    }
                }
            }
        });
      canvasP.onclick = function(e) {
        var slice = piChart.getElementAtEvent(e);
        if (!slice.length) return; // return if not clicked on slice
        var label = slice[0]._model.label;
        var url = "{% url 'dashboard:recipe_search' 'search_type' 'label_placeholder' %}"
        url = url.replace('search_type', encodeURIComponent('time'));
        url = url.replace('label_placeholder', encodeURIComponent(label));
        window.location.href = url;
      }
   </script>
  </body>
</html>

mysite/dashboard/templates/serach_result.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>만개의 레시피 재료 분석</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/lumen/bootstrap.min.css" />
    <!-- Chart Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- WordCloud -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wordcloud2.js/1.2.2/wordcloud2.min.js"></script>
  </head>
  <style>
    .card {
      transition: transform 0.2s;
    }
    .card:hover {
      transform: scale(1.05);
    }
  </style>
  <body>
    {% block navbar %}
      {% include 'header.html' %}
    {% endblock %}

    <!-- Navigation -->
    <div class="container px-4 px-lg-5 mt-5">
      {% if search_type == 'time' %}
        <h2 class="fw-bolder mb-4">예상 조리 시간 "{{ chart_label }}"인 요리 검색 결과</h2>
      {% elif search_type == 'ingredient' %}
        <h2 class="fw-bolder mb-4">요리 재료로 "{{ chart_label }}"를 사용하는 요리 검색 결과</h2>
      {% else %}
        <h2 class="fw-bolder mb-4">검색 타입이 다릅니다</h2>
      {% endif %}

      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
        {% comment %} {% endcomment %}
        {% for r_recipe in search_result_recipe %}
          <div class="col mb-5">
            <div class="card h-100">
              <!-- Product image -->
              <a href="{% url 'dashboard:recipe_detail' r_recipe.id %}"><img class="card-img-top" src="{{ r_recipe.image_url }}" alt="{{ r_recipe.recipe_title }}" width="300" height="200" /></a>
              <!-- Product details -->
              <div class="card-body p-4">
                <div class="text-center">
                  <!-- Product name -->
                  <h6 class="fw-bolder">{{ r_recipe.recipe_title }}</h6>
                </div>
              </div>
              <!-- Product actions -->
              <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center">
                  <a class="btn btn-outline-dark mt-auto" href="{% url 'dashboard:recipe_detail' r_recipe.id %}">레시피 확인하기</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        {% comment %} {% endcomment %}
      </div>
    </div>

    <!-- Footer -->
    <footer class="py-3 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">재형 효정 주호</p>
      </div>
    </footer>
  </body>
</html>